# Generated by Django 4.1.7 on 2023-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=128)),
                ("input_data", models.CharField(max_length=10000)),
                ("full_response", models.CharField(max_length=10000)),
                ("response", models.CharField(max_length=10000)),
                ("feedback", models.CharField(blank=True, max_length=10000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
